# Generated by Django 5.2.11 on 2026-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFTemplateElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_name",
                    models.CharField(
                        choices=[
                            ("logo", "Company Logo"),
                            ("company_info", "Company Info (Name/Address)"),
                            ("jobcard_details", "Jobcard # & Date"),
                            ("client_details", "Client Name"),
                            ("technician_details", "Technician Name"),
                            ("times", "Start/Stop Times"),
                            ("items_table", "Items Table"),
                            ("manager_notes", "Manager Notes"),
                            ("admin_notes", "Admin Notes"),
                            ("signatures", "Signatures Block"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("pos_x", models.FloatField(default=0.0)),
                ("pos_y", models.FloatField(default=0.0)),
                ("width", models.FloatField(default=100.0)),
                ("height", models.FloatField(default=50.0)),
                ("font_size", models.IntegerField(default=10)),
            ],
        ),
    ]
