# Generated by Django 5.2.11 on 2026-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0002_pdftemplateelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdftemplateelement",
            name="element_name",
            field=models.CharField(
                choices=[
                    ("header_logo", "Company Logo"),
                    ("company_info", "Company Info (Name/Address)"),
                    ("jobcard_meta", "Jobcard Details (Num/Date)"),
                    ("client_details", "Client Details"),
                    ("start_stop_times", "Start/Stop Times"),
                    ("items_table", "Items Table"),
                    ("manager_notes", "Manager Notes"),
                    ("admin_notes", "Admin Notes"),
                    ("signatures", "Signatures Block"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
