# Generated by Django 5.2.11 on 2026-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0003_alter_pdftemplateelement_element_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="tech_notes",
            field=models.TextField(blank=True),
        ),
    ]
