# Generated by Django 5.2.11 on 2026-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0004_jobcard_tech_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="watermark",
            field=models.ImageField(blank=True, null=True, upload_to="watermarks/"),
        ),
    ]
