# Generated by Django 5.2.11 on 2026-02-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0005_globalsettings_watermark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobcards.company",
            ),
        ),
    ]
