# Generated by Django 5.2.11 on 2026-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0006_alter_jobcard_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
