# Generated by Django 5.2.11 on 2026-03-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0007_jobcard_client_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobcard",
            name="client_email",
        ),
    ]
